### ISSUE TITLE
[verify&publish] returns 500

### ISSUE THREAD

**Issue by nicolegys** [ZhangTao1596/blockscout#4]
click [verify&publish],
![1682244329091](https://user-images.githubusercontent.com/43694095/233833347-02347907-2dc5-4e3b-9cdf-7f83e2d079f4.png)
then,
![1682244390634](https://user-images.githubusercontent.com/43694095/233833381-387d1795-cf97-4c6d-abb6-00246d095ff0.png)

**Comment by ZhangTao1596** [comment]
Fixed. `SCRET_KEY_BASE`
