### ISSUE TITLE
Write Contract失败

### ISSUE THREAD

**Issue by nicolegys** [ZhangTao1596/blockscout#8]
Write Contract失败
![image](https://user-images.githubusercontent.com/43694095/237014589-ac4730ab-9fdd-45ff-a841-24bde4396892.png)

http://evm.ngd.network/address/0xe4E37311669Bf7Ab3F7059c009E8d0298E27B910/write-contract#address-tabs

**Comment by ZhangTao1596** [comment]
Fixed

**Comment by nicolegys** [comment]
test ok
